#logging
options:
  logging: CLOUD_LOGGING_ONLY
steps:
    # Install
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    # Build
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
    # Deploy
    - name: 'asia-south1-docker.pkg.dev/fh-dev-svc/fh-dev-svc-firebase/firebase'
      args: ['deploy', '--project=fh-dev-svc', '--only=hosting:fh-dev-medplum-hosting']